### ISSUE TITLE
New release to be able to use weighted synonyms

### ISSUE THREAD

**Issue by thiagobrandam** [querqy/querqy-elasticsearch#12]
Hi, querqy folks !

It seems that querqy implemented weighted synonyms back on January 2021 (https://github.com/querqy/querqy/pull/134) but there's no release on the querqy-elasticsearch project to use this new feature as of now.

Let me know if I can be of any help !

Thanks

**Comment by renekrie** [comment]
Hi @thiagobrandam,

Weighted synonyms are already available in the Querqy for ES code base. The plan is to cut a release in ca. 2-3 weeks when https://github.com/querqy/querqy-elasticsearch/issues/11 has been finalised. Do let us know if it is more urgent.

Thank you for offering help. I think we are fine for weighted synonyms. I'd be interested in feedback to #11 or, if you feel like a bit of Querqy coding, https://github.com/querqy/querqy-elasticsearch/issues/10 might be a good starting point. We also have a querqy-dev channel on the  E-commerce Search Slack (https://ecom-search.slack.com - I'm always uncertain if new members need an invitation or if you can just join - do let me know if you need an invitation.)

**Comment by thiagobrandam** [comment]
Hi @renekrie , thanks for the prompt response ! It's all good, turns out I ended up building project's HEAD on my development machine (I used the pom instructions) and it works like a charm :) 

Sure thing, I'll try to help the project though my Java fu is a bit rusty !

I tried to joined that slack workspace and I think I need an invitation ... would you be kind to invite me through thiagobrandam at gmail ?

**Comment by renekrie** [comment]
Released. See versions 1.4.es7*
