### ISSUE TITLE
[querqy] unknown field [multi_match]

### ISSUE THREAD

**Issue by pasupathi-rajamanickam-odp** [querqy/querqy-elasticsearch#57]
We are heavily using multi match with field boost. Do we have similar option?

```
{
    "querqy": {
        "multi_match": {
            "fields": [
                "title^60",
                "description^60",
                "id^40",
                "name^30",
                "category^25",
                "short_description^10"
            ],
            "operator": "and",
            "query": "taner",
            "type": "most_fields"
        },
        "rewriters": [
            "replace",
            "common_rules"
        ]
    }
}
```

**Comment by renekrie** [comment]
Yes:

```
{
    "querqy": {
        "matching_query": {
             "query": "taner"
         },
         "query_fields": [
                "title^60",
                "description^60",
                "id^40",
                "name^30",
                "category^25",
                "short_description^10"
            ],
            "minimum_should_match": "100%"
        },
        "rewriters": [
            "replace",
            "common_rules"
        ]
    }
}
```

The matching strategy is similar to `most_fields` (works as expected, also if analyzers differ between fields) and the score aggregation across fields can be controlled by a `tie_breaker` param. There are a lot more params that you can use to control scoring - see here for details: https://querqy.org/docs/querqy/more-about-queries.html#querqy-more-about-queries

**Comment by renekrie** [comment]
I'm now seeing the title for the issue @pasupathi-rajamanickam-odp. Querqy is a query builder on its own, it extends the ES DSL with its own params. You don't wrap a multi_match inside!

**Comment by renekrie** [comment]
I assume that I can close this issue. Feel free to create a new one/reopen in case of further questions.
