### ISSUE TITLE
Create version for ES 8.5.3

### ISSUE THREAD

**Issue by pasupathi-rajamanickam-odp** [querqy/querqy-elasticsearch#59]
Can I use https://repo1.maven.org/maven2/org/querqy/querqy-elasticsearch/1.6.es852.0/ for 853?

**Comment by renekrie** [comment]
We had been waiting for https://github.com/querqy/querqy-elasticsearch/pull/55 to be merged, which has just happened, so I expect the release still this week. I'm changing the issue title.

You cannot use 852 for 853 as ES requires the exact version to be specified in the plugin manifest in the .zip. If you cannot wait, you could unpack the .zip, change the manifest and .zip it. Apart from this, the version should be compatible.

**Comment by pasupathi-rajamanickam-odp** [comment]
Awesome thanks for the workaround.

**Comment by pasupathi-rajamanickam-odp** [comment]
@renekrie Did we get a chance to publish ES 8.5.3?
