### ISSUE TITLE
Create version for ES 8.6.2

### ISSUE THREAD

**Issue by Leaf-Lin** [querqy/querqy-elasticsearch#71]
Hi, 

This is a feature request issue. I'm hoping there will be a release of 8.6.2 plugin available soon. Thanks!

 https://github.com/querqy/querqy-elasticsearch/pull/63

**Comment by renekrie** [comment]
@Leaf-Lin Sorry, your request must have slipped my/our attention. Do you still need Querqy for this specific ES version? - I'm just releasing one for ES 8.9.2

**Comment by Leaf-Lin** [comment]
No worries. This is no longer required. Thanks.
