### ISSUE TITLE
Elasticsearch 7.17.11

### ISSUE THREAD

**Issue by hexa2k9** [querqy/querqy-elasticsearch#75]
Hello,

we're currently looking into running some Elasticsearch Updates on the 7.x branch. I saw there's Querqy 1.5 for Elasticsearch 7.17.2 available. Is there any Chance you can build and publish a Version built against 7.17.11 (current latest 7.17, [released yesterday](https://github.com/elastic/elasticsearch/releases/tag/v7.17.11))?

Thanks in advance.

**Comment by renekrie** [comment]
Hi @hexa2k9 , Sorry that we got behind the ES releases. I will work on it this week.

**Comment by hexa2k9** [comment]
No worries. I created a version compatible to 7.17.11 so our Search folks can start testing compatibility. Feel free to [pull it in](https://github.com/hexa2k9/querqy-elasticsearch/tree/es71711) if you want. Tests passed just fine locally.

**Comment by renekrie** [comment]
Why don't you make it a pull request then? - I'd be glad to give visibility to other folks' contributions

**Comment by hexa2k9** [comment]
It's open now with `es7172` as a target branch (which it was created from). 
I didn't originally create one due to the lack of a named branch for `.11`.

**Comment by renekrie** [comment]
Released - should show up on Maven Central and in docs shortly.

**Comment by hexa2k9** [comment]
Thank you.
